version: '3'
services:
  marquez-api:
    image: marquezproject/marquez:0.50.0
    container_name: marquez-api
    hostname: marquez-api
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
    ports:
      - "5000:5000"
    links:
      - "marquez-db:postgres"
    depends_on:
      - marquez-db
    networks:
      - private-cloud
  marquez-web:
    image: marquezproject/marquez-web:0.50.0
    container_name: marquez-web
    hostname: marquez-web
    environment:
      - MARQUEZ_HOST=api
      - MARQUEZ_PORT=5000
      - WEB_PORT=4000
      - REACT_APP_ADVANCED_SEARCH=true
    ports:
      - "4000:4000"
    depends_on:
      - marquez-api
    networks:
      - private-cloud
  marquez-db:
    image: postgres:14
    container_name: marquez-db
    hostname: marquez-db
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]
    networks:
      - private-cloud

networks:
  private-cloud:
    name: private-cloud
    driver: bridge