version: '3'
services:
  grafana-dashboards:
    image: grafana/grafana:11.3.0
    container_name: grafana-dashboards
    hostname: grafana-dashboards
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
      - GF_LOG_MODE=console file
    networks:
      private-cloud:
  grafana-loki:
    image: grafana/loki:3.1.2
    container_name: grafana-loki
    hostname: grafana-loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yaml:/mnt/config/local-config.yaml
    command: -config.file=/mnt/config/local-config.yaml
    networks:
      private-cloud:
  grafana-promtail:
    image: grafana/promtail:3.1.2
    container_name: grafana-promtail
    hostname: grafana-promtail
    volumes:
      - ../workspace/logs:/workspace/logs
      - ./config/promtail.yaml:/mnt/config/config.yaml
    command: -config.file=/mnt/config/config.yaml
    networks:
      private-cloud:

networks:
  private-cloud:
    name: private-cloud
    driver: bridge