name: opensource-containerized-stack

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:25.1.2
    container_name: cloudbeaver
    hostname: cloudbeaver
    volumes:
      - ./config/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
      # - ./drivers/hive:/opt/cloudbeaver/drivers/hive
    ports:
      - "8978:8978"
    networks:
      - private-cloud

networks:
  private-cloud:
    driver: bridge
    name: private-cloud