name: opensource-containerized-stack

services:
  datanode:
    image: apache/ozone:1.4.0
    ports:
      - "9864"
    command: ["ozone","datanode"]
    env_file:
      - ./docker-config
    deploy:
      replicas: 1
    networks:
      - private-cloud
  ozone-om:
    image: apache/ozone:1.4.0
    container_name: ozone-om
    hostname: ozone-om
    ports:
      - "9874:9874"
    environment:
      ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
      WAITFOR: ozone-scm:9876
    env_file:
      - ./docker-config
    command: ["ozone","om"]
    networks:
      - private-cloud
  ozone-scm:
    image: apache/ozone:1.4.0
    container_name: ozone-scm
    hostname: ozone-scm
    ports:
      - "9876:9876"
    env_file:
      - ./docker-config
    environment:
      ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
    command: ["ozone","scm"]
    networks:
      - private-cloud
  ozone-recon:
    image: apache/ozone:1.4.0
    container_name: ozone-recon
    hostname: ozone-recon
    ports:
      - "9888:9888"
    env_file:
      - ./docker-config
    command: ["ozone","recon"]
    networks:
      - private-cloud
  ozone-s3g:
    image: apache/ozone:1.4.0
    container_name: ozone-s3g
    hostname: ozone-s3g
    ports:
      - "9878:9878"
    env_file:
      - ./docker-config
    command: ["ozone","s3g"]
    networks:
      - private-cloud
  ozone-httpfs:
    image: apache/ozone:1.4.0
    container_name: ozone-httpfs
    hostname: ozone-httpfs
    ports:
      - "14000:14000"
    env_file:
      - ./docker-config
    command: ["ozone","httpfs"]
    networks:
      - private-cloud

networks:
  private-cloud:
    name: private-cloud
    driver: bridge