name: opensource-containerized-stack

services:
  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    user: root
    ports:
      - 8888:8888
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    networks:
      - private-cloud

networks:
  private-cloud:
    name: private-cloud
    driver: bridge